### ISSUE TITLE
On Ubuntu 14, you have to install the nodejs-legacy package

### ISSUE THREAD

**Issue by starbuck93** [maddox/dasher#10]
Will you add under "Dasher app -- Simply clone and install the dependencies." that this package is required? 

`sudo apt-get install nodejs-legacy`

Here's the link to the apparent reason, for anyone curious. http://stackoverflow.com/questions/21168141/can-not-install-packages-using-node-package-manager-in-ubuntu

**Comment by maddox** [comment]
This project works fine on the latest node. I don't think this is needed.

Thanks!
