### ISSUE TITLE
Dasher not loaded after reboot in El Capitan

### ISSUE THREAD

**Issue by sofauxboho** [maddox/dasher#14]
On El Capitan (10.11.3) Dasher would run be loaded when installed with script/install but would not be loaded again by launchd after a reboot. As such, it  stopped working every time I rebooted the server.

The service name was present when running "sudo launchctl list | grep -i dasher" before a reboot, but  was entirely missing when running the same command after reboot. Installing again would bring it back up, but it would disappear again after the next reboot.

This appears to be due to the way Apple has mucked about with launchd recently.

This fixed it (at least for me):
Move Dasher launchd plist from LaunchAgents to LaunchDaemons
"mv /Library/LaunchAgents/org.dasher.plist /Library/LaunchDaemons"
Load into launchd with new bootstrap command:
"sudo launchctl bootstrap system /Library/LaunchDaemons/org.dasher.plist"

**Comment by maddox** [comment]
> sudo launchctl bootstrap system /Library/LaunchDaemons/org.dasher.plist

Oh interesting, does this get it to launch on boot without logging into the system?

**Comment by sofauxboho** [comment]
I believe it should according to the documentation. Launches as a system daemon, not at any gui or user level. Can test this evening.
