### ISSUE TITLE
how to disable post to amazon

### ISSUE THREAD

**Issue by hartogsmith** [maddox/dasher#20]
thanks for this, your instructions and code worked well for me -- i'm able to hit ifttt and do what i wanted to do, but amazon still knows the button is being pressed and sends a "finish setting up your dash" notification on every press, which is messy traffic on top of my ifttt notification  -- any plans to intercept and squelch that call to amazon?

**Comment by maddox** [comment]
You have to do that in your amazon app. You need to disconnect the dash button from your account.

You can see instructions here: https://github.com/hortinstein/node-dash-button#first-time-dash-setup

This is of course for initial setup. I'm sure google can help you for buttons that have already been associated.

**Comment by hartogsmith** [comment]
hey, thanks for getting back. i did disable notifications on the amazon app
and that's great. was still wondering if preventing the post to amazon
wouldn't help discourage amazon from reworking things in some way that
creates problems for everyone using the buttons for fun. thanks for your
work on this!

**Comment by maddox** [comment]
As far as I know, it doesn't post to Amazon anymore. ¯\(°_o)/¯

**Comment by Flavien** [comment]
> You need to disconnect the dash button from your account.

I tried disconnecting the dash button from my account, and after a day, it no longer connects to the wifi (and stops triggering Dasher).

**Comment by qrioniclabs** [comment]
> I tried disconnecting the dash button from my account, and after a day, it no longer connects to the wifi (and stops triggering Dasher). The LED just flashes red when I press the button.

I can confirm this. Taking dash button out of Amazon app makes it stop working.

Notifications can be disabled within the app. Still looking for a way to prevent Amazon from sending me an email telling me to finish the setup everytime the button is being pressed.

**Comment by vsidlu** [comment]
Please let everyone know if you find how to disable thees emails! Thanks in advance!

**Comment by qrioniclabs** [comment]
> Please let everyone know if you find how to disable thees emails! Thanks in advance!

Will do. For the moment, I have created a mail policy deleting every mail with the dash buttons device number instantly...
