### ISSUE TITLE
BLE support?

### ISSUE THREAD

**Issue by oneweak7words** [maddox/dasher#24]
I got your dasher setup working beautifully on my rpi2, with auto-startup. 
I'm new to github so pardon if this is the wrong place. Was wondering, with the rpi3 out now, if you've considered using BLE with node to expand the project. I've been reading on the Misfit Flash/Link (recently on sale from manufacturer for $5/ $3) and thinking with the ability for multiple functions (single press, double press, etc) that it would be an excellent next expansion/evolution for this project.

**Comment by maddox** [comment]
Thanks for the suggestion! But the project probably won't be expanding outside of dash buttons.
