### ISSUE TITLE
How to do something different?

### ISSUE THREAD

**Issue by ez2remember** [maddox/dasher#30]
Can I use this to check whether either of my cell phones is connected to my wifi at 11 pm every night, then if it is, trigger the maker channel URL?

For example:

At 11:00 PM, if [MAC ADDRESS 1] or [MAC ADDRESS 2] is connected to [WIFI NETWORK] then [IFTTT MAKER CHANNEL URL]

**Comment by maddox** [comment]
There are other means to do that in an automated fashion. Check out https://home-assistant.io
