### ISSUE TITLE
Works when it auto starts, error when launching 'npm run start' (Raspi)

### ISSUE THREAD

**Issue by junior466** [maddox/dasher#69]
Hello,

I am running dasher on a Raspberry Pi 3 and receive the following error when running the `sudo npm run start`

`npm ERR! Linux 4.4.50-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start"
npm ERR! node v4.8.1
npm ERR! npm  v2.15.11
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log
`

But when I use `sudo /etc/init.d/dasher start`, it works perfectly.

**Comment by cbarth3** [comment]
I am seeing the same thing on a new install.

**Comment by maddox** [comment]
it doesn't look like you're in the correct directory when running `sudo npm run start`

**Comment by junior466** [comment]
Yep, turned out to be it. Thank you.
