### ISSUE TITLE
Amazon dash does nothing when press

### ISSUE THREAD

**Issue by hazenote** [maddox/dasher#73]
Hello (again) Sorry for bad english im from france !

Now 90 percent of this is working ^^

but when i launch i got 

> dasher@1.3.0 start /home/bell/dasher
> node app.js

[2017-04-22T14:01:06.158Z] Porte added.

And even if i press there is nothing hapening :-/ 

Here is my configuration ! ( a friend gave it to me so i don't know if it's okay)

{"buttons":[
  {
    "name": "Porte",
    "address": "your:dash:mac:40:B4:CD:87:CE:F4
    "url": "$
    "method": "POST"
  }
]}

i know the ifttt url is correct bcs i can launch it manually with chrome.

can someone help ? thx ^^

**Comment by wikijm** [comment]
Hi @hazenote,

Could you please use "Insert code" functionnality to share your code?
It's seems you get an " missing on line 4 at the end of line.

P.S: I'm a frenchie too, if it's help to talk our native language 😉

**Comment by hazenote** [comment]
`{"buttons":[
  {
    "name": "Porte",
    "address": "your:dash:mac:40:B4:CD:87:CE:F4",
    "url": "https://maker.ifttt.com/trigger/ring/with/key/jzS0-t1onxgJMuu6Q2jL1373JbQ68igF4tU-PkO8U6w",
    "method": "POST"
  }
]}`


Tu parle fr aussi c'est ca que tu veux dire ? 

c'est bien de le mettre sous forme de code que tu m'as demandé ? desolé je suis un peu nouveau ici :-)

**Comment by hazenote** [comment]
@wikijm On c'est pas deja croiser sur le topic de chez jarvis par hasard ?  ou alors l'addon livebox tv de jarvis justement ?

**Comment by wikijm** [comment]
@hazenote 
- Ma langue natale est le français
- C'est bien ça pour la fonctionnalité "Insert code", mais ça t'a fait perdre les sauts de ligne bizarrement 😞 
- Je suis contributeur du projet [alexylem/jarvis](https://github.com/alexylem/jarvis), du coup oui sans doute sur le  plugin [LiveboxTV](http://domotiquefacile.fr/jarvis/plugins/liveboxtv) ou [Freebox Revolution Player](http://domotiquefacile.fr/jarvis/search/content/freebox) 😉

**Comment by chimpy** [comment]
@hazenote 

Solution assez simple :) L'adresse MAC doit contenir juste ça. L'exemple est à remplacer en fait.

`"address": "40:B4:CD:87:CE:F4"`

Ca devrait marcher!

**Comment by hazenote** [comment]
Merci beaucoup ca marche *-* merci merci

**Comment by chimpy** [comment]
D'ailleurs, tu devrais supprimer l'URL de ton post *et* probablement renouveler l'adresse dans IFTTT (je n'utilise pas donc je pourrais pas te dire comment faire) parce que n'importe qui peut cliquer sur cet URL et déclencher ton événement 😱

**Comment by hazenote** [comment]
ah oui j'avais pas penser a ca :x

merci @chimpy et @wikijm

**Comment by wikijm** [comment]
Et clôturer le ticket aussi 😉 
Je confirme ce que dis @chimpy, y'a moyen de s'amuser avec ton URL IFTTT 😜

**Comment by hazenote** [comment]
ne le faites pas 😜 c'est une sonnette ^^ merci en tout cas
