### ISSUE TITLE
Error: Error: No devices to listen

### ISSUE THREAD

**Issue by junior466** [maddox/dasher#76]
Started receiving this error after upgrading to Ubiquiti Edgerouter.
Have tried adding  "protocol" but no luck.

Any suggestions?

**Comment by junior466** [comment]
Got rid of the error after removing "protocol" but button press are not being registered.

**Comment by daniel-stoneuk** [comment]
Did you use "protocol": "all"

**Comment by junior466** [comment]
For some weird reason its all back to normal.
