### ISSUE TITLE
Triggering Keyboard Maestro workflows

### ISSUE THREAD

**Issue by kitze** [maddox/dasher#8]
Keyboard maestro uses this kind of urls 

http://192.168.1.124:4490/action.html?macro=786B4E60-8D79-44A0-8E42-8482569DB9D0

So you can execute macros locally on the mac. But i can't execute it with dasher because i'm getting 

"not a 200
null"

This error. I tried setting the request to get/post but it still doesn't work. Is a fix possible for this?

Btw. Thank you very much for this, it's so useful! :)

**Comment by maddox** [comment]
Dasher doesn't actually do anything with errors, it just reports them. You can see [here](https://github.com/maddox/dasher/blob/master/lib/dasher.js#L42).

So while Keyboard Maestro isn't returning a `200`, whatever request you're sending it should work just fine.
