### ISSUE TITLE
What if I want to add two dash buttons?

### ISSUE THREAD

**Issue by LastHitchhiker** [maddox/dasher#82]
How are you, guys?
I'm a novice interested of home-automation and recently doing connecting dash buttons to ifttt.
This tutorial is really informative to me and successfully I can use ONE dash button.
However, if I want to use two dash buttons, how should I edit config.json?

I tried like the **following:
*1st try

{"buttons":[
  {
    "name": "clif",
    "address": "XX:XX:XX:XX:XX:XX",
    "url": "https://maker.ifttt.com/trigger/clif_pressed/with/key/MYKEYYYYYYY
    "method": "POST"
  }
]}
{"buttons":[
  {
    "name": "gato",
    "address": "XX:XX:XX:XX:XX:XX",
    "url": "https://maker.ifttt.com/trigger/gato_pressed/with/key/MYKEYYYYYYY
    "method": "POST"
  }
]}

*2nd try
{"buttons":[
  {
    "name": "clif",
    "address": "XX:XX:XX:XX:XX:XX",
    "url": "https://maker.ifttt.com/trigger/clif_pressed/with/key/MYKEYYYYYYY
    "method": "POST"
  },
  {
    "name": "gato",
    "address": "XX:XX:XX:XX:XX:XX",
    "url": "https://maker.ifttt.com/trigger/gato_pressed/with/key/MYKEYYYYYYY
    "method": "POST"
  }
]}

Both tries showed the same error message like:
module.js:453
    throw err;
    ^

SyntaxError: /home/pi/dasher/config/config.json: Unexpected token 

    at Object.parse (native)
    at Object.Module._extensions..json (module.js:450:27)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/pi/dasher/app.js:2:14)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

npm ERR! Linux 4.9.28-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! dasher@1.4.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dasher@1.4.1 start script 'node app.js'.
npm ERR! This is most likely a problem with the dasher package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls dasher
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/dasher/npm-debug.log

Thanks for the reading mine. And I need your help, professionals :)

**Comment by maddox** [comment]
Your configuration is incorrect, you need to keep all of your buttons nested under the `buttons` key in the JSON.

```json
{
  "buttons": [
    { "name": "clif",
      "address": "XX:XX:XX:XX:XX:XX",
      "url": "https://maker.ifttt.com/trigger/clif_pressed/with/key/MYKEYYYYYYY",
      "method": "POST"
    },
    { "name": "gato",
      "address": "XX:XX:XX:XX:XX:XX",
      "url": "https://maker.ifttt.com/trigger/gato_pressed/with/key/MYKEYYYYYYY",
      "method": "POST"
    }
  ]
}
```

**Comment by LastHitchhiker** [comment]
Thanks a lot. Until now I tried a lot and now I can fix the problem.
First, keep all of your buttons nested under the buttons key in the JSON.
Second, I missed " and , at the end of the "url" section.
Now every this is perfect.
Thank you very much!! Maddox

Lee from South Korea

**Comment by maddox** [comment]
👍 👍 👍
