### ISSUE TITLE
Dasher detects multiple button presses

### ISSUE THREAD

**Issue by w1ll1am23** [maddox/dasher#9]
When I start Dasher the below lines print
single element detected
Open Garge Door added.
 
Then when I press the button I get the below line
Open Garge Door pressed.

Then approximately 30-40 seconds later I get the following two line and the HA scene is run again.
Open Garge Door pressed.
Open Garge Door pressed.

Any idea how to fix this? I see something similar when running the find button. I get the following output from one button press.

possible dash hardware address detected:  10:ae:60:XX:XX:XX
possible dash hardware address detected:  10:ae:60:XX:XX:XX
~ 30 seconds passes then the below 2 print out.
possible dash hardware address detected:  10:ae:60:XX:XX:XX
possible dash hardware address detected:  10:ae:60:XX:XX:XX

**Comment by robbiet480** [comment]
Same thing here, would be good to add a configurable timeout.

**Comment by w1ll1am23** [comment]
Under lib there is a dasher.js I added sleep(6000) as the last line of the DasherButton function and that seems to have fixed my problem. However, it now takes longer for the request to get processed. I wonder why others haven't reported this issue. robbiet480, can you explain how your network is setup? I have a pfsense router/firewall with a ddwrt AP, and dasher running on a ubuntu 14.04 box.

**Comment by maddox** [comment]
This should be fixed by #13 with upgrading `node-dash-button` and possibly the ability to specify the interface to listen on.

If it looks like it's still detecting multiple button presses, feel free to re-open this.

Thanks!
